# Form implementation generated from reading ui file 'addSaving_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(504, 368)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.cbbEmergency = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cbbEmergency.setObjectName("cbbEmergency")
        self.cbbEmergency.addItem("")
        self.cbbEmergency.addItem("")
        self.cbbEmergency.addItem("")
        self.cbbEmergency.addItem("")
        self.verticalLayout.addWidget(self.cbbEmergency)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.txtAmount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtAmount.setObjectName("txtAmount")
        self.verticalLayout.addWidget(self.txtAmount)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.txtDate = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtDate.setObjectName("txtDate")
        self.verticalLayout.addWidget(self.txtDate)
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.txtNote = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtNote.setObjectName("txtNote")
        self.verticalLayout.addWidget(self.txtNote)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ptnOK = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ptnOK.setObjectName("ptnOK")
        self.horizontalLayout.addWidget(self.ptnOK)
        self.ptnCancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ptnCancel.setObjectName("ptnCancel")
        self.horizontalLayout.addWidget(self.ptnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 504, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Categorry:"))
        self.cbbEmergency.setItemText(0, _translate("MainWindow", "Emergency"))
        self.cbbEmergency.setItemText(1, _translate("MainWindow", "Goal"))
        self.cbbEmergency.setItemText(2, _translate("MainWindow", "General"))
        self.cbbEmergency.setItemText(3, _translate("MainWindow", "Other"))
        self.label_2.setText(_translate("MainWindow", "Amount:"))
        self.label_3.setText(_translate("MainWindow", "Date:"))
        self.label_4.setText(_translate("MainWindow", "Note:"))
        self.ptnOK.setText(_translate("MainWindow", "OK"))
        self.ptnCancel.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
