# Form implementation generated from reading ui file 'ui_files/Inter_Saving.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.cbbCategory = QtWidgets.QComboBox(parent=Dialog)
        self.cbbCategory.setObjectName("cbbCategory")
        self.cbbCategory.addItem("")
        self.cbbCategory.addItem("")
        self.cbbCategory.addItem("")
        self.cbbCategory.addItem("")
        self.verticalLayout.addWidget(self.cbbCategory)
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.txtAmount = QtWidgets.QLineEdit(parent=Dialog)
        self.txtAmount.setObjectName("txtAmount")
        self.verticalLayout.addWidget(self.txtAmount)
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.txtDate = QtWidgets.QLineEdit(parent=Dialog)
        self.txtDate.setObjectName("txtDate")
        self.verticalLayout.addWidget(self.txtDate)
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.txtNote = QtWidgets.QLineEdit(parent=Dialog)
        self.txtNote.setObjectName("txtNote")
        self.verticalLayout.addWidget(self.txtNote)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnOK = QtWidgets.QPushButton(parent=Dialog)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout.addWidget(self.btnOK)
        self.btnCancel = QtWidgets.QPushButton(parent=Dialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Categorry:"))
        self.cbbCategory.setItemText(0, _translate("Dialog", "Emergency"))
        self.cbbCategory.setItemText(1, _translate("Dialog", "Goal"))
        self.cbbCategory.setItemText(2, _translate("Dialog", "General"))
        self.cbbCategory.setItemText(3, _translate("Dialog", "Other"))
        self.label_2.setText(_translate("Dialog", "Amount:"))
        self.label_3.setText(_translate("Dialog", "Date:"))
        self.label_4.setText(_translate("Dialog", "Note:"))
        self.btnOK.setText(_translate("Dialog", "OK"))
        self.btnCancel.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
